-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 14:53:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bacsilog` DEFAULT CHARACTER SET utf8 ;
USE `bacsilog` ;

-- -----------------------------------------------------
-- Table `bacsilog`.`franchisee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`franchisee` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fran_fname` VARCHAR(20) NULL,
  `fran_lname` VARCHAR(20) NULL,
  `fran_birthday` DATE NULL,
  `fran_address` VARCHAR(20) NULL,
  `fran_salary` INT(10) NULL,
  `fran_email` VARCHAR(20) NULL,
  `fran_num` INT(12) NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`franchise_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`franchise_fee` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fran_fee_amount` INT(10) NULL,
  `fran_fee_receipt` INT(10) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`royalty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`royalty` (
  `id` INT NOT NULL,
  `royal_date` DATE NULL,
  `royal_expiry` DATE NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`license` (
  `id` INT(10) NOT NULL,
  `lic_code` INT(10) NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`document_agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`document_agreement` (
  `id` INT(10) NOT NULL,
  `da_date` DATE NULL,
  `da_status` VARCHAR(10) NULL,
  `da_duration` DATE NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
