-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 14:52:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bacsilog` DEFAULT CHARACTER SET utf8 ;
USE `bacsilog` ;

-- -----------------------------------------------------
-- Table `bacsilog`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`form` (
  `id` INT(10) NOT NULL AUTO_INCREMENT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`management` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `manage_dept` VARCHAR(10) NULL,
  `manage_employee` VARCHAR(10) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
