-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 14:53:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bacsilog` DEFAULT CHARACTER SET utf8 ;
USE `bacsilog` ;

-- -----------------------------------------------------
-- Table `bacsilog`.`training_agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`training_agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ta_dept` VARCHAR(10) NOT NULL,
  `ta_staff` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`executive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`executive` (
  `exec_dept` INT(10) NOT NULL,
  `exec_staff` VARCHAR(50) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`finance` (
  `fin_dept` INT NOT NULL,
  `fin_staff` VARCHAR(50) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`financial_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`financial_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fr_status` VARCHAR(45) NOT NULL,
  `fr_salary` DECIMAL(10,2) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loc_address` VARCHAR(50) NULL,
  `loc_status` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
