-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 13:41:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bacsilog` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`executive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`executive` (
  `exec_dept` INT(10) NOT NULL,
  `exec_staff` VARCHAR(50) NOT NULL,
  `id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`finance` (
  `fin_dept` INT NOT NULL,
  `fin_staff` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`fin_dept`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`franchisee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`franchisee` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fran_fname` VARCHAR(20) NULL DEFAULT NULL,
  `fran_lname` VARCHAR(20) NULL DEFAULT NULL,
  `fran_birthday` DATE NULL DEFAULT NULL,
  `fran_address` VARCHAR(20) NULL DEFAULT NULL,
  `fran_salary` INT(10) NULL DEFAULT NULL,
  `fran_email` VARCHAR(20) NULL DEFAULT NULL,
  `fran_num` INT(12) NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `management_id` INT(10) NOT NULL,
  `document_agreement_id` INT(10) NOT NULL,
  `form_id` INT(10) NOT NULL,
  `location_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `franchisee_id`, `management_id`, `document_agreement_id`, `form_id`, `location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stall` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stall_address` VARCHAR(50) NULL,
  `loc_status` VARCHAR(10) NOT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  `franchisee_management_id` INT(10) NOT NULL,
  `franchisee_document_agreement_id` INT(10) NOT NULL,
  `franchisee_form_id` INT(10) NOT NULL,
  `franchisee_location_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_location_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC, `franchisee_management_id` ASC, `franchisee_document_agreement_id` ASC, `franchisee_form_id` ASC, `franchisee_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id` , `franchisee_management_id` , `franchisee_document_agreement_id` , `franchisee_form_id` , `franchisee_location_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id` , `management_id` , `document_agreement_id` , `form_id` , `location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`management` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `manage_dept` VARCHAR(10) NULL DEFAULT NULL,
  `manage_employee` VARCHAR(10) NULL DEFAULT NULL,
  `location_id` INT NOT NULL,
  `executive_id` INT(10) NOT NULL,
  `finance_fin_dept` INT NOT NULL,
  `location_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `location_id`, `executive_id`, `finance_fin_dept`),
  INDEX `fk_management_executive1_idx` (`executive_id` ASC) VISIBLE,
  INDEX `fk_management_finance1_idx` (`finance_fin_dept` ASC) VISIBLE,
  INDEX `fk_management_location1_idx` (`location_id1` ASC) VISIBLE,
  CONSTRAINT `fk_management_executive1`
    FOREIGN KEY (`executive_id`)
    REFERENCES `mydb`.`executive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_management_finance1`
    FOREIGN KEY (`finance_fin_dept`)
    REFERENCES `mydb`.`finance` (`fin_dept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_management_location1`
    FOREIGN KEY (`location_id1`)
    REFERENCES `mydb`.`stall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training_agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training_agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ta_dept` VARCHAR(10) NOT NULL,
  `ta_staff` VARCHAR(10) NOT NULL,
  `management_id` INT(10) NOT NULL,
  `management_location_id` INT NOT NULL,
  `management_executive_id` INT(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `management_id`, `management_location_id`, `management_executive_id`),
  INDEX `fk_training_agent_management1_idx` (`management_id` ASC, `management_location_id` ASC, `management_executive_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_agent_management1`
    FOREIGN KEY (`management_id` , `management_location_id` , `management_executive_id`)
    REFERENCES `bacsilog`.`management` (`id` , `location_id` , `executive_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financial_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financial_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fr_status` VARCHAR(45) NOT NULL,
  `fr_salary` DECIMAL(10,2) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `bacsilog` ;

-- -----------------------------------------------------
-- Table `bacsilog`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`form` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  `franchisee_management_id` INT(10) NOT NULL,
  `franchisee_document_agreement_id` INT(10) NOT NULL,
  `franchisee_form_id` INT(10) NOT NULL,
  `franchisee_location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_form_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC, `franchisee_management_id` ASC, `franchisee_document_agreement_id` ASC, `franchisee_form_id` ASC, `franchisee_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_form_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id` , `franchisee_management_id` , `franchisee_document_agreement_id` , `franchisee_form_id` , `franchisee_location_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id` , `management_id` , `document_agreement_id` , `form_id` , `location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`franchise_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`franchise_fee` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fran_fee_amount` INT(10) NULL DEFAULT NULL,
  `fran_fee_receipt` INT(10) NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  `franchisee_management_id` INT(10) NOT NULL,
  `franchisee_document_agreement_id` INT(10) NOT NULL,
  `franchisee_form_id` INT(10) NOT NULL,
  `franchisee_location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_franchise_fee_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC, `franchisee_management_id` ASC, `franchisee_document_agreement_id` ASC, `franchisee_form_id` ASC, `franchisee_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_franchise_fee_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id` , `franchisee_management_id` , `franchisee_document_agreement_id` , `franchisee_form_id` , `franchisee_location_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id` , `management_id` , `document_agreement_id` , `form_id` , `location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`royalty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`royalty` (
  `id` INT NOT NULL,
  `royal_date` DATE NULL DEFAULT NULL,
  `royal_expiry` DATE NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  `franchisee_management_id` INT(10) NOT NULL,
  `franchisee_document_agreement_id` INT(10) NOT NULL,
  `franchisee_form_id` INT(10) NOT NULL,
  `franchisee_location_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_royalty_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC, `franchisee_management_id` ASC, `franchisee_document_agreement_id` ASC, `franchisee_form_id` ASC, `franchisee_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_royalty_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id` , `franchisee_management_id` , `franchisee_document_agreement_id` , `franchisee_form_id` , `franchisee_location_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id` , `management_id` , `document_agreement_id` , `form_id` , `location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`license` (
  `id` INT(10) NOT NULL,
  `lic_code` INT(10) NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  `franchisee_management_id` INT(10) NOT NULL,
  `franchisee_document_agreement_id` INT(10) NOT NULL,
  `franchisee_form_id` INT(10) NOT NULL,
  `franchisee_location_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_license_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC, `franchisee_management_id` ASC, `franchisee_document_agreement_id` ASC, `franchisee_form_id` ASC, `franchisee_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_license_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id` , `franchisee_management_id` , `franchisee_document_agreement_id` , `franchisee_form_id` , `franchisee_location_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id` , `management_id` , `document_agreement_id` , `form_id` , `location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`document_agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`document_agreement` (
  `id` INT(10) NOT NULL,
  `da_date` DATE NULL DEFAULT NULL,
  `da_status` VARCHAR(10) NULL DEFAULT NULL,
  `da_duration` DATE NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  `franchisee_management_id` INT(10) NOT NULL,
  `franchisee_document_agreement_id` INT(10) NOT NULL,
  `franchisee_form_id` INT(10) NOT NULL,
  `franchisee_location_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_document_agreement_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC, `franchisee_management_id` ASC, `franchisee_document_agreement_id` ASC, `franchisee_form_id` ASC, `franchisee_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_agreement_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id` , `franchisee_management_id` , `franchisee_document_agreement_id` , `franchisee_form_id` , `franchisee_location_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id` , `management_id` , `document_agreement_id` , `form_id` , `location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`franchisee_has_management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`franchisee_has_management` (
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  `franchisee_management_id` INT(10) NOT NULL,
  `franchisee_document_agreement_id` INT(10) NOT NULL,
  `franchisee_form_id` INT(10) NOT NULL,
  `franchisee_location_id` INT NOT NULL,
  `management_id` INT(10) NOT NULL,
  `management_location_id` INT NOT NULL,
  `management_executive_id` INT(10) NOT NULL,
  `management_finance_fin_dept` INT NOT NULL,
  PRIMARY KEY (`franchisee_id`, `franchisee_franchisee_id`, `franchisee_management_id`, `franchisee_document_agreement_id`, `franchisee_form_id`, `franchisee_location_id`, `management_id`, `management_location_id`, `management_executive_id`, `management_finance_fin_dept`),
  INDEX `fk_franchisee_has_management_management1_idx` (`management_id` ASC, `management_location_id` ASC, `management_executive_id` ASC, `management_finance_fin_dept` ASC) VISIBLE,
  INDEX `fk_franchisee_has_management_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC, `franchisee_management_id` ASC, `franchisee_document_agreement_id` ASC, `franchisee_form_id` ASC, `franchisee_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_franchisee_has_management_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id` , `franchisee_management_id` , `franchisee_document_agreement_id` , `franchisee_form_id` , `franchisee_location_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id` , `management_id` , `document_agreement_id` , `form_id` , `location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franchisee_has_management_management1`
    FOREIGN KEY (`management_id` , `management_location_id` , `management_executive_id` , `management_finance_fin_dept`)
    REFERENCES `bacsilog`.`management` (`id` , `location_id` , `executive_id` , `finance_fin_dept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`management_has_stall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`management_has_stall` (
  `management_id` INT(10) NOT NULL,
  `management_location_id` INT NOT NULL,
  `management_executive_id` INT(10) NOT NULL,
  `management_finance_fin_dept` INT NOT NULL,
  `stall_id` INT NOT NULL,
  PRIMARY KEY (`management_id`, `management_location_id`, `management_executive_id`, `management_finance_fin_dept`, `stall_id`),
  INDEX `fk_management_has_stall_stall1_idx` (`stall_id` ASC) VISIBLE,
  INDEX `fk_management_has_stall_management1_idx` (`management_id` ASC, `management_location_id` ASC, `management_executive_id` ASC, `management_finance_fin_dept` ASC) VISIBLE,
  CONSTRAINT `fk_management_has_stall_management1`
    FOREIGN KEY (`management_id` , `management_location_id` , `management_executive_id` , `management_finance_fin_dept`)
    REFERENCES `bacsilog`.`management` (`id` , `location_id` , `executive_id` , `finance_fin_dept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_management_has_stall_stall1`
    FOREIGN KEY (`stall_id`)
    REFERENCES `mydb`.`stall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`management_has_financial_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`management_has_financial_review` (
  `management_id` INT(10) NOT NULL,
  `management_location_id` INT NOT NULL,
  `management_executive_id` INT(10) NOT NULL,
  `management_finance_fin_dept` INT NOT NULL,
  `financial_review_id` INT NOT NULL,
  PRIMARY KEY (`management_id`, `management_location_id`, `management_executive_id`, `management_finance_fin_dept`, `financial_review_id`),
  INDEX `fk_management_has_financial_review_financial_review1_idx` (`financial_review_id` ASC) VISIBLE,
  INDEX `fk_management_has_financial_review_management1_idx` (`management_id` ASC, `management_location_id` ASC, `management_executive_id` ASC, `management_finance_fin_dept` ASC) VISIBLE,
  CONSTRAINT `fk_management_has_financial_review_management1`
    FOREIGN KEY (`management_id` , `management_location_id` , `management_executive_id` , `management_finance_fin_dept`)
    REFERENCES `bacsilog`.`management` (`id` , `location_id` , `executive_id` , `finance_fin_dept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_management_has_financial_review_financial_review1`
    FOREIGN KEY (`financial_review_id`)
    REFERENCES `mydb`.`financial_review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
