-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 14:05:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bacsilog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bacsilog` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`training_agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training_agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ta_dept` VARCHAR(10) NOT NULL,
  `ta_staff` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`executive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`executive` (
  `exec_dept` INT(10) NOT NULL,
  `exec_staff` VARCHAR(50) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`finance` (
  `fin_dept` INT NOT NULL,
  `fin_staff` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`fin_dept`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loc_address` VARCHAR(50) NULL,
  `loc_status` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`management` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `manage_dept` VARCHAR(10) NULL DEFAULT NULL,
  `manage_employee` VARCHAR(10) NULL DEFAULT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`, `location_id`),
  INDEX `fk_management_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_management_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financial_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financial_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fr_status` VARCHAR(45) NOT NULL,
  `fr_salary` DECIMAL(10,2) NOT NULL,
  `management_id` INT(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `management_id`),
  INDEX `fk_financial_review_management_idx` (`management_id` ASC) VISIBLE,
  CONSTRAINT `fk_financial_review_management`
    FOREIGN KEY (`management_id`)
    REFERENCES `bacsilog`.`management` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bacsilog` ;

-- -----------------------------------------------------
-- Table `bacsilog`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`form` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`document_agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`document_agreement` (
  `id` INT(10) NOT NULL,
  `da_date` DATE NULL DEFAULT NULL,
  `da_status` VARCHAR(10) NULL DEFAULT NULL,
  `da_duration` DATE NULL DEFAULT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`franchisee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`franchisee` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fran_fname` VARCHAR(20) NULL DEFAULT NULL,
  `fran_lname` VARCHAR(20) NULL DEFAULT NULL,
  `fran_birthday` DATE NULL DEFAULT NULL,
  `fran_address` VARCHAR(20) NULL DEFAULT NULL,
  `fran_salary` INT(10) NULL DEFAULT NULL,
  `fran_email` VARCHAR(20) NULL DEFAULT NULL,
  `fran_num` INT(12) NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `management_id` INT(10) NOT NULL,
  `document_agreement_id` INT(10) NOT NULL,
  `form_id` INT(10) NOT NULL,
  `location_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `franchisee_id`, `management_id`, `document_agreement_id`, `form_id`, `location_id`),
  INDEX `fk_franchisee_management1_idx` (`management_id` ASC) VISIBLE,
  INDEX `fk_franchisee_document_agreement1_idx` (`document_agreement_id` ASC) VISIBLE,
  INDEX `fk_franchisee_form1_idx` (`form_id` ASC) VISIBLE,
  INDEX `fk_franchisee_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_franchisee_management1`
    FOREIGN KEY (`management_id`)
    REFERENCES `bacsilog`.`management` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franchisee_document_agreement1`
    FOREIGN KEY (`document_agreement_id`)
    REFERENCES `bacsilog`.`document_agreement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franchisee_form1`
    FOREIGN KEY (`form_id`)
    REFERENCES `bacsilog`.`form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franchisee_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`franchise_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`franchise_fee` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fran_fee_amount` INT(10) NULL DEFAULT NULL,
  `fran_fee_receipt` INT(10) NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `franchisee_id`, `franchisee_franchisee_id`),
  INDEX `fk_franchise_fee_franchisee_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC) VISIBLE,
  CONSTRAINT `fk_franchise_fee_franchisee`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`royalty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`royalty` (
  `id` INT NOT NULL,
  `royal_date` DATE NULL DEFAULT NULL,
  `royal_expiry` DATE NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `franchisee_id`, `franchisee_franchisee_id`),
  INDEX `fk_royalty_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC) VISIBLE,
  CONSTRAINT `fk_royalty_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacsilog`.`license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bacsilog`.`license` (
  `id` INT(10) NOT NULL,
  `lic_code` INT(10) NULL DEFAULT NULL,
  `franchisee_id` INT(10) NOT NULL,
  `franchisee_franchisee_id` INT(10) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `franchisee_id`, `franchisee_franchisee_id`),
  INDEX `fk_license_franchisee1_idx` (`franchisee_id` ASC, `franchisee_franchisee_id` ASC) VISIBLE,
  CONSTRAINT `fk_license_franchisee1`
    FOREIGN KEY (`franchisee_id` , `franchisee_franchisee_id`)
    REFERENCES `bacsilog`.`franchisee` (`id` , `franchisee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
